### ISSUE TITLE
Redundant doc comment tag is not working correctly

### ISSUE THREAD

**Issue by laurin1** [funivan/PhpClean#107]
Example:

![image](https://user-images.githubusercontent.com/75857/81064694-c25c6200-8e9f-11ea-835c-49c821cbf77e.png)

If I remove the doc comment, ```@param TicketsSubmitForm $oTicketsData```, I get this:

![image](https://user-images.githubusercontent.com/75857/81064778-e9b32f00-8e9f-11ea-8a42-d0c782b4679f.png)

**Comment by funivan** [comment]
Argument PHPDoc missing is owned by PhpStorm team. Try to configure `PHPDoc comments matches..` inspection
![image](https://user-images.githubusercontent.com/425208/81657685-bbee5d00-9440-11ea-9bb7-e08cd29897e4.png)

**Comment by laurin1** [comment]
> Argument PHPDoc missing is owned by PhpStorm team. 

Yes, but my point was it appeared I could only use one or the other - Redundant doc comment tag or PHPDoc missing - but not both. Seems that the native inspections should always be considered "authoritative". However, I did try the PHPDoc comment matches previously and it had no effect, yet I just tried it again and now all seems like it's work as it should be.

**Comment by funivan** [comment]
Yes, you need to decide what inspection you want to use.

Also keeping mind that PhpStorm team release its own inspection Redundant doc comment 
https://blog.jetbrains.com/phpstorm/2020/04/phpstorm-2020-1-release/
Fill free to try it.

**Comment by laurin1** [comment]
I'm using that one as well, but that one only does all or nothing.

**Comment by laurin1** [comment]
Just to be clear, I now have all of these enabled and no conflict.

**Comment by funivan** [comment]
> I'm using that one as well, but that one only does all or nothing.

Can you give more detail what PhpStorm inspection cant perform?  Or why it is not applicable in your case.

**Comment by laurin1** [comment]
The PhpStorm inspection only flags those PHPDoc comments that are completely redundant - meaning, it won't do this one, but yours will:

![image](https://user-images.githubusercontent.com/75857/81931783-41444f80-95b0-11ea-90ee-a611e62f7d74.png)

See your inspection flags 2 of the 3 parameters as redundant, but PhpStorm instead warns of a missing type declaration (and until union types are here, we can't declare $rSQL).

**Comment by funivan** [comment]
I have created an issue https://youtrack.jetbrains.com/issue/WI-53537
It would be cool if they can expand the inspection and delete doc tags one by one.
