### ISSUE TITLE
Release new version of plugin that contains c081a78df14862aaa1b7eb6169503f2fcd32a39e

### ISSUE THREAD

**Issue by wbars** [funivan/PhpClean#108]
Hi! We've released PhpStorm 2020.2 EAP, in this version we had to introduce API-breaking change: remove `com.jetbrains.php.lang.psi.elements.PhpReturnType#getClassReference` method. Luckily, only one usage in this plugin was found in `src/main/kotlin/com/funivan/idea/phpClean/constrains/method/aliases/NamedConstructor.kt` and as I can see this code was already removed in c081a78df14862aaa1b7eb6169503f2fcd32a39e. Can you please release new version of the plugin so we could drop this method completely while it has no usages? Thank you!

**Comment by funivan** [comment]
Yep, I will do that. Thanks.

**Comment by funivan** [comment]
Done, waiting for approval.
