### ISSUE TITLE
"Assign missused" inspection is wrong

### ISSUE THREAD

**Issue by TrueXakeP** [funivan/PhpClean#129]
With the last 2020.11.05-alpha I get the "Assignment and comparison operators used in one statement" warning at 3d line in this example, while there is no comparison operation:
```php
<?php
$i = $j = $cols = 0;
$currMenuPos = $j * $cols + $i;
```
![image](https://user-images.githubusercontent.com/5345528/98234545-4aafe280-1f69-11eb-8812-3566f3518ed1.png)

Same with this single line:
```php
$img = 'images/' . $imgBase . '/' . $item->getImage($btnType, $pictPrefix);
```

Also in this line:
```php
$this->rootId = $rootGroupId ?? $manager->getRootNodeId();
```

Same here:
```php
$menuListLandscapeHeight = 100 / $actualLandscapeRows;
```

And I think that here is too:
```php
$this->view->params['isMainMenu']    = $menu->getPid() === null;
```

**Comment by funivan** [comment]
Thanks for the report. 👍

**Comment by TrueXakeP** [comment]
I'm embarrassed to ask, what is the test case for this inspection? Because with 2020.11.6-nightly I don't see any warnings here:
```php
if ($i = 10) {
    echo 'test';
}
```

And also I don't see this warning in the example from the readme:
```php
do{
 //...
}while( $isValid = $user->getName() == self::ADMIN_USER );
 // ^^^ Hard to read this statements
```

![изображение](https://user-images.githubusercontent.com/5345528/98471500-734c0c80-21f5-11eb-9234-33e0cad638fe.png)

**Comment by funivan** [comment]
@TrueXakeP I will fix the description before the release. 
After a conversation with some folks, I have decided to cover following cases:
```php
$a === $b = $c;
$a !== $b = $c;
$a == $b = $c;
$a != $b = $c;
```
no matter where they are used (in if or while statements)
