### ISSUE TITLE
Remove docblock opening/closing tag when removing the last content tag

### ISSUE THREAD

**Issue by orklah** [funivan/PhpClean#134]
Hi!

Could it be possible to remove the whole docblock when the inspection "Redundant doc comment tag" removes the last tag of the block?

Currently, there's
```
/**
 */
```
left after the inspection that must be removed

Thanks!

**Comment by funivan** [comment]
Yep. It is possible.

**Comment by funivan** [comment]
Implemented https://plugins.jetbrains.com/plugin/11272-phpclean/versions/stable/106135

You can update plugin in the IDE.

**Comment by orklah** [comment]
Thanks!
