### ISSUE TITLE
Property can be private is invalid

### ISSUE THREAD

**Issue by laurin1** [funivan/PhpClean#135]
![image](https://user-images.githubusercontent.com/75857/100286030-a4d41000-2f37-11eb-81f6-d02320d162e3.png)

But that trait is used in \Intranet\Pages\ClientDashboard:

![image](https://user-images.githubusercontent.com/75857/100286058-b1586880-2f37-11eb-9356-d2f11b830825.png)

Property is used here (child of \Intranet\Pages\ClientDashboard)

![image](https://user-images.githubusercontent.com/75857/100286083-bfa68480-2f37-11eb-9ddf-60e253218dea.png)

**Comment by laurin1** [comment]
I've got many examples like this one that are being flagged but are not valid.

**Comment by funivan** [comment]
Thanks. This is definitely a bug. I will fix it next week.

**Comment by funivan** [comment]
Hello. I have released nightly version with the fix https://github.com/funivan/PhpClean/releases/tag/2020.11.30-nightly You can download the JAR file and `Install plugin from disk`. 
After some time I will release a public version of the plugin (probably 2020.12.04)

**Comment by funivan** [comment]
Released.

https://plugins.jetbrains.com/plugin/11272-phpclean/versions/stable/104345
