### ISSUE TITLE
Issue with union type in last EAP

### ISSUE THREAD

**Issue by orklah** [funivan/PhpClean#143]
Hi,

In last EAP, it seems that Union Types are considered as object with __toString.

For example, I get a `Deprecated __toString call` on this code:

`$var= 'a' . preg_replace('/_[A-Z]{3,}$/', '', $b);`

**Comment by funivan** [comment]
Thanks for the report. I will check it.

**Comment by funivan** [comment]
PR from @ChrisGalliano #146 should resolve this issue. 

@ChrisGalliano can you add tests for this particular case?)

**Comment by ChrisGalliano** [comment]
@funivan, no problem if you think it's necessary.
But in my opinion, it doesn't make sense. We removed the checking functions feature from this inspection, so the test will only protect us from accidentally adding this functionality in the future.

**Comment by funivan** [comment]
Fixed: https://plugins.jetbrains.com/plugin/11272-phpclean/versions/stable/138437
