### ISSUE TITLE
use configured php version of phpstorm for types

### ISSUE THREAD

**Issue by uehler** [funivan/PhpClean#145]
I'm working on a project which still uses php7.0.
There are unit tests and other methods, which don't return anything. PhpClean suggests to add a return type but `void` isn't supported in php7.0.

The php version for the project is defined in composer and in PhpStorm (External Libraries -> right click -> configure php include paths). The plugin should use one of those version (if based on composer use the lowest supported php version) to only show the inspections supported by the used php version.

**Comment by funivan** [comment]
Hello @uehler 
You are talking about MissingReturnType inspection?

**Comment by uehler** [comment]
ah yes, i do

**Comment by funivan** [comment]
In your case, it is better to disable this inspection in your project. 
Because it depends not only on the project level but also in the namespace (directory)
We have a directory with all Events and there are no void types, so inspection works fine for this Scope. And for other scopes, it is just disabled.

**Comment by uehler** [comment]
but if i disable the inspections I don't have it for string, int and the other types.

Because I have phpstorm and php inspections turned on, it isn't that much of a problem turning that inspection off. I'm fine with that, your plugin is a great extension to those other plugins! Keep going! :)

**Comment by funivan** [comment]
@uehler I get the point. It is theoretically possible to check if we have `void` and PHP version does not support this.

But anyway, I highly recommend upgrading to the latest supported version https://www.php.net/supported-versions.php

**Comment by uehler** [comment]
upgrade to php8 would be nice, but because its a legacy project, we have to stay at 7.0 for now...
