### ISSUE TITLE
"Use assert" inspection bug

### ISSUE THREAD

**Issue by asgraf** [funivan/PhpClean#156]
```PHP
/** @var \Cake\Collection\Collection<\App\Model\Entity\User> $users */
```
Comments like this trigger "Use assert to check variable type" inspection
After pressing alt+enter on such a comment and selecting "Use assert" comment gets deleted and no assert is placed in it's place

If I'm honest, I don't know what such an assertion would even look like if it worked

**Comment by funivan** [comment]
Yeah, it will be hard to build an pure PHP assert approach for the generic variables. 
It is a rule of thumb to use some libraries like assert from WebMozart 
https://github.com/webmozarts/assert#collection-assertions

I think disabling alt+enter is a good choice here.
