### ISSUE TITLE
"use assert" inspection shoud place asserts below variable declaration

### ISSUE THREAD

**Issue by asgraf** [funivan/PhpClean#162]
Example code:
```php
/** @var \ExampleClass $variableName */
$variableName = $this->someMethod();
```
What i get after using `use assert` inspection:
```php
assert($variableName instanceof \ExampleClass);
$variableName = $this->someMethod();
```
What i expect after using `use assert` inspection:
```php
$variableName = $this->someMethod();
assert($variableName instanceof \ExampleClass);
```
Assert shoud be placed after not before variable is set
Current behavior causes error on line 1 because $variableName is not defined

**Comment by funivan** [comment]
Hi. I have fixed the issue. In a few days, I'll release the plugin.

**Comment by funivan** [comment]
https://plugins.jetbrains.com/plugin/11272-phpclean/versions/stable/314039
You can download the new version of the plugin.

The main goal was not to break PHP code and I have disabled QF (quick fix) for this specific case. 
Moving the statement down might be not the best option, For example, I have seen cases where an assign statement has 5-10 lines of the code, it means assert should be placed down. It can bring confusion.
