### ISSUE TITLE
MethodShouldBeFinal should not apply to anonymous classes

### ISSUE THREAD

**Issue by allanlaal** [funivan/PhpClean#163]
version: 2021.09.26

this inspection is triggered on methods in PHP anonymous classes:
  
	  return new final class 
	  {
  
		  public function I_do_not_have_to_be_final () : void
		  {
			  ...
		  }

	  };

since anon classes can't be extended, there is no need to set the final keyword for its methods

**Comment by allanlaal** [comment]
location to fix:
https://github.com/funivan/PhpClean/blob/c081a78df14862aaa1b7eb6169503f2fcd32a39e/src/main/kotlin/com/funivan/idea/phpClean/inspections/methodShouldBeFinal/MethodShouldBeFinalInspection.kt#L17

is there a `phpClass.isAnonymous` ?

**Comment by funivan** [comment]
Thank for the ticket @allanlaal 
Let me check what we can do here.

**Comment by funivan** [comment]
This bug will be fixed in 2022.08.30 

I have created a release and waiting  for approval from JetBrains
