### ISSUE TITLE
[FR] Missing parameter type for PHP < 7

### ISSUE THREAD

**Issue by orklah** [funivan/PhpClean#73]
Hey!

I'm not sure if you're interested in supporting PHP versions < 7 with this plugin, or even if you're interested in suggestions, but I'll give it a try!

We have a big legacy code at work who run in PHP 5.3 for now. We're in the process of migrating to PHP 7.2 but it's a big project and it's not the main preoccupation when there's business who need new features.

To make sure we won't break anything, we began with a lot of code cleaning. PhpStorm helped a lot with that, and PHP EA helped very much too. I like your plugin for personnal projects but except "PhpClean undefined method" inspection, it's not very relevant with our work codebase. For starters, it suggest adding return types and scalar type hints when our PHP version don't allow it yet, so we had to disable those inspections

However, we would need a similar inspection to make our code cleaner. We have a lot of code like this:
```php
class foo{
    function bar($var){
        $var->do_a_thing();
    }
}
```
While we generally have types in PHPDoc, we don't have a lot of type hints. It's a shame because we can't always be sure we receive an object in the method (some methods can receive multiple types, including scalars).
So what we would need is an inspection that tell us to add a type hint only when the parameter seem to be used as an object directly.

For example, the previous code would be flagged, but ideally this would not:
```php
class foo{
    function bar($var){
        if(!is_object($var)){
            echo $var;
        }
        $var->do_a_thing();
    }
}
```

The Quickfix could be to just add object before the variable name, but the warning only should be enough.

Feel free to close if it's too specific or if you're not interested in old PHP versions :)

**Comment by funivan** [comment]
First of all thanks for the feedback @orklah 
Inspection PhpCleanUndefinedMethod tries to cover more cases then standard phpstorm inspection Undefined method. 

Sorry but disabled inspection is the best case for you. Maybe after adding return types you can enable it and find some bugs.
