### ISSUE TITLE
Annotation for exclusion of return types requirement for function and parameters for the method

### ISSUE THREAD

**Issue by fux666** [funivan/PhpClean#8]
Hi! Currently I have a problem where the method from the closed library gets overloaded, when a child class is inherited from it we are in one of two situations: 
1) There are no types specified and PHPClean alerts of this as a problem, or
2) The types are added but then PHP comlaints that the method definition has changed.

It is recommended, that in such case or any other where parameter or return definition is not possible (e.g. parameter taking both string and integer) it is possible to silence the inspections with the annotation. Example of such implementation may be:

        /**
         * @param string $psRequest **@suppress(MissingParameterTypeInspection)**
         * @param string $prTarget  **@suppress(MissingParameterTypeInspection)**
         * ......
         * @return mixed|string
         * @throws SoapFault
         */
        function __doRequest($psRequest, $prTarget, ...) {

In a perfect world, it would be possible to also have a parameter that specify a regexp expression as parameter of the inspection, following variations of Hungarian Notation coding standards, that would match parameters of particular pattern to be excluded for the type requirement in my case all this parameters would be e.g. pm% and functions fm% prefixed - that would always be excluded from type missing inspection.

**Comment by funivan** [comment]
fixed
