### ISSUE TITLE
Deprecated __toString call: new patterns

### ISSUE THREAD

**Issue by orklah** [funivan/PhpClean#99]
Hi,

There are some other patterns that could be matched with the __toString inspection

None of the following are matched:
```php
<?php
class a{
    public function __toString()
    {
        $debug = debug_backtrace();
        echo "__toString called on line ".$debug['0']['line']."\n";
        return "";
    }
}

function string_param(string $a){

}

function object_param(object $a){
    echo $a; //here
    (string)$a; //here
    $a == "0"; //here
    string_param($a); //here
    ?><?= $a; ?><?php //here
}

$a = new a();
$a == "0"; //here
string_param($a); //here
object_param($a);
```

https://3v4l.org/F4qIL

If it help, I can try to create a PR with failing tests.

Thanks!

**Comment by funivan** [comment]
Hello. I will try to cover some cases.

**Comment by orklah** [comment]
Great!

**Comment by funivan** [comment]
Hello @orklah 
I have covered several cases. You can see tests here https://github.com/funivan/PhpClean/tree/master/src/test/kotlin/com/funivan/idea/phpClean/inspections/toStringCall

The only case I have skipped is `string_param($a);` It can be a performance slowdown. Don't know how to fix it right now.

In a couple of days, I will make a release.

**Comment by orklah** [comment]
Great! Thanks a lot!

**Comment by orklah** [comment]
If I'm not mistaken, there was no release recently. Can we expect it soon?

Thanks

**Comment by funivan** [comment]
Hello @orklah 
I forgot to close the issue. Check the latest plugin version 2020.06.03
![image](https://user-images.githubusercontent.com/425208/93760571-f351ef00-fc14-11ea-97a0-7637278597fc.png)

**Comment by orklah** [comment]
Thanks!
